apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    database: flowforge
    user: default
    secureJsonData:
      password: clickhouse
    jsonData:
      defaultDatabase: flowforge
      port: 8123
  - name: MongoDB
    type: grafana-mongodb-datasource
    access: proxy
    url: mongodb://admin:password@mongodb:27017
    database: flowforge
